pipeline {
 agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: dind-builder-pod
spec:
  containers:
  - name: tools
    image: python:3.12-slim
    imagePullPolicy: IfNotPresent
    command:
      - sleep
    args:
      - infinity
  - name: dind
    image: docker:dind
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    command:
      - dockerd-entrypoint.sh
    args:
      - "--iptables=false"
      - "--bridge=none"
      - "--insecure-registry=zot.local"
    volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
  volumes:
  - name: dind-storage
    emptyDir: {}
"""
        }
    }

    stages {
        stage('Check workspace') {
            steps {
                sh 'echo "Checking workspace files:" && ls -la'
            }
        }

        stage('Build and Push Backend image') {
            steps {
                container('dind') {
                    sh '''
                        until docker info > /dev/null 2>&1; do
                            echo "Waiting for docker daemon..."
                            sleep 2
                        done
                        cd backend
                        docker build -t zot.local/aiops-backend:v1.0.0-${BUILD_NUMBER} .
                        docker push zot.local/aiops-backend:v1.0.0-${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Build and Push UI image') {
            steps {
               container('dind') {
                    sh '''
                        until docker info > /dev/null 2>&1; do
                            echo "Waiting for docker daemon..."
                            sleep 2
                        done
                        cd ui
                        docker build -t zot.local/aiops-ui:v1.0.0-${BUILD_NUMBER} .
                        docker push zot.local/aiops-ui:v1.0.0-${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Update Helm Values and Git Push') {
            steps {
                container('tools') {
                    withCredentials([usernamePassword(credentialsId: 'git-credentials',
                                                      usernameVariable: 'GIT_USERNAME',
                                                      passwordVariable: 'GIT_PASSWORD')]) {
                        sh '''
                            apt-get update && apt-get install -y git && pip install --no-cache-dir pyyaml

                            git config --global --add safe.directory /home/jenkins/agent/workspace/aiops-deploy-platform-app
                            git config --global user.name "Dima Pochin"
                            git config --global user.email "gitlab_admin_5e326f@example.com"
                            git config http.sslVerify false

                            python3 -c "
import yaml
path = 'k8s/ai-ops-platform-chart/values.yaml'
with open(path, 'r') as f:
    data = yaml.safe_load(f)

if 'backend' in data and 'image' in data['backend']:
    data['backend']['image']['tag'] = 'v1.0.0-${BUILD_NUMBER}'
if 'ui' in data and 'image' in data['ui']:
    data['ui']['image']['tag'] = 'v1.0.0-${BUILD_NUMBER}'

with open(path, 'w') as f:
    yaml.safe_dump(data, f, sort_keys=False)
"
                            git add k8s/ai-ops-platform-chart/values.yaml
                            git commit -m "CI: Update image tags to build ${BUILD_NUMBER}"
                            git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@gogs.local/gogs/ai-ops-platform-app.git
                            git push origin HEAD:main
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Successfully built, pushed images, and updated Helm values in Git."
        }
        failure {
            echo "Pipeline failed during build or Git operations."
        }
    }
}
