apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-platform-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gogs.gogs.svc.cluster.local:3000/gogs/ai-ops-platform-app.git'
    targetRevision: main
    path: k8s/ai-ops-platform-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aiops-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true